services:

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: 4419855
    image: mongo
    networks:
      - db_network
    restart: always
    volumes:
      - ./db/data:/db/data

  mongo-express:
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: 4419855
      ME_CONFIG_MONGODB_URL: mongodb://dbuser:4419855@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    image: mongo-express
    networks:
      - db_network
    ports:
      - 8081:8081
    restart: unless-stopped

networks:
  db_network:
    driver: bridge


    

